### ISSUE TITLE
Support GenisysPro

### ISSUE THREAD

**Issue by Crypt97** [ProjectInfinity/PocketLotto#1]
Please Support GenisysPro server software !

**Comment by ProjectInfinity** [comment]
GenisysPro has not proven itself as worth my time, officially I will only support PMMP.

Also when checking them out they are flat out lying about what GenisysPro is, it IS a fork of PocketMine yet they say it isn't.

Quoted from their github page:

> FYI: Being that this is NOT a PMMP fork, test your plugins first then submit issues to https://github.com/GenisysProPlugins 

How come their source is the PMMP source? https://github.com/GenisysPro/GenisysPro/tree/master/src

If they managed to break plugins by forking PMMP and making stupid changes then I refuse to support them.

**Comment by Crypt97** [comment]
Please no :'(
