### ISSUE TITLE
Update to 3.3.0

### ISSUE THREAD

**Issue by kevinishawesome** [ProjectInfinity/PocketLotto#5]
Please bump API!

**Comment by ProjectInfinity** [comment]
API has been updated to 3.0.0 which should work, however Github seems to have some problems delivering webhooks at the moment so it does not seem like Poggit has picked up on the commits. Will have to give it some time.

**Comment by kevinishawesome** [comment]
Yes, GitHub had issues yesterday, but every is back to normal now.. I tested your latest build.. and everything works great now! Thanks,
